language: python
sudo: false
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.5"

python:
  - 2.7

install:
  - pip install virtualenv
  - virtualenv env
  - env/bin/pip install -U pip setuptools zc.buildout
  - env/bin/python -c 'import sys; print sys.version_info'
  - >
    env/bin/buildout
    versions:zc.buildout= versions:setuptools=

script: bin/nosetests karl

cache:
  directories:
    - $HOME/.cache/pip
    - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
