language: python
sudo: false
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.5"

python:
  - 2.7

install:
  - virtualenv env
  - env/bin/pip install -U pip setuptools zc.buildout
  - env/bin/buildout versions:zc.buildout= versions:setuptools= versions:ZEO=

script: bin/nosetests karl

cache:
  directories:
    - $HOME/.cache/pip
    - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
